:PROPERTIES:
:ID:       350DE913-3D01-434E-942F-388FE7A66A7B
:END:
#+title: Fiora's notes on meditation
[[file:20210212104344-meditation.org][Meditation]], [[file:20210206161400-public_notes.org][Public Notes]], [[file:20210212104750-fioraaeterna.org][FioraAeterna]]

[[https://twitter.com/FioraAeterna/status/1270804899748409344]]

* Preparations
1. *find a comfortable posture.* my personal favorite is just to lie down, head propped up with a pillow.
2. *make sure you're awake enough that you won't just fall asleep.* caffeine is fine.
3. *if you can, make sure you can breathe through your nose easily.* use oxymetazoline (nose drops) if you have to. the more effortless nose-breathing is, the easier this will be.
* Meditation
1. get into your preferred posture (as I said, I lie down) and start breathing through your nose only. gently, calmly, one breath at a time. get used to this. 2. once you're used to this pattern of breathing, focus on the sensation of the air going through your nose. try to pay attention to that, and lust that, for a few seconds.
3. now, and this is critical, *don't try hard to do this.* just pay attention to the sensation, feel it, and let go. "letting go" means you're no longer trying to focus on it; you're just letting your focus drift from whatever you were doing, but not aiming it at anything else either.
4. at first, your focus is probably going to drift extremely fast, in seconds or less. this is completely normal. *don't force yourself to hold focus.* instead, let your focus drift.
5. at some point, you will notice that you are clearly no longer paying attention to the breath. it may take you minutes to actually notice this at first, even if it your attention drifts in seconds. this is fine.
6. *when this happens, this is not a failure, this is success.* your task here is to set your focus, let it drift, and then catch it when it drifts, and notice whatever you started thinking about or paying attention to instead.
7. now, pull focus back on the nose and breath, and start again. it's okay if this whole cycle takes 15 seconds or less. you're going to be doing it a lot.

* Path
1. as you practice, your ability to notice the drift will slowly improve, and your ability to stay longer without drifting will improve. this cannot come from lrying hard"; it con only come from training your brain (which can only happen if you don't try hard).
2. now, eventually, you'll be able to lie down or sit for 10, 15, 20+ minutes, and as you do, thoughts will rise to the surface, you'll notice them, and then you'll return to the breath.
3. as you do this, in a longer session, it will be as if you're releasing layers and layers of pent-up thoughts; *letting things out, without giving yourself any new input to create new thoughts*. so over these minutes, you will start to become more and more empty.
4. eventually you may reach a point at which things start to get a little weird -- you're here but you're not "thinking" or "doing" anything at all. if you're not thinking or doing anything, what are you?
5. and thus begins your joumey into meditation.

* Disclaimer
Do not follow any of these instructions religiously, because they are only as "correct" as your interpretation of them, which (almost definitionally) will not be the same as no interpretation of them. your brain is different from mine, so you will need to explore.

By the way, this is one interpretation of the classic koan If you meet the buddha in the road, kill him".
