#+title: Dual Power
[[file:20210206161400-public_notes.org][Public Notes]]

"Dual power" frameworks are about how to build sustainable power in parallel opposition to an existing hegemonous power.

'Forming a new world "in the shell of the old."'

In the context of leftist organizing DSA-LSC (not sure if i like/trust this group) says there are two parts to a dual power framework:
1. "*Building counter-institutions* that serve as alternatives to the institutions currently governing production, investment, and social life under capitalism"
2. "Organizing through and *confederating these institutions* to *build up a base of grassroots counter-power* which can eventually challenge the existing power of capitalists and the state head-on"

But what's interesting to me is the implementation details, not the ideal. The word "building" in point 1, and the words "organizing through" and "confederating."
- How does one specifically *build* resilient community?
- What does "organizing THROUGH" a community mean, specifically? How can we leverage an existing community to organize its power?


Feels like a "master's tools cannot destroy the master's house" situation.


- "Within and outside of": four words that seem very significant to describe how this works

The later part of the doc describes how to build such powers:
- Entryism: Entering into your already-existing civic institutions (neighborhood councils, associations, block clubs, etc) and injecting them with direct-democratic anti-authoritarian and anti-capitalist goals and processes

- Creating our own councils and popular assemblies based on material conditions that demand action: going door-to-door and meeting with people, and assessing them where they're at

Anyways, what do you *do* with dual power frameworks?

In the DSA-LSC group:
- *Delegitimize* the larger power in the eyes of observers
